[package]
name = "evil_crc32c"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "evil_crc32c"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36"

[features]
nif_version_2_15 = ["rustler/nif_version_2_15"]
nif_version_2_16 = ["rustler/nif_version_2_16"]
